// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Provider struct {
	ID   int64
	Name sql.NullString
}

type Voucher struct {
	ID         int64
	GroupID    int64
	Username   string
	Validity   int64
	Expirytime sql.NullInt64
	Starttime  sql.NullFloat64
	Endtime    sql.NullInt64
	Printed    string
	State      string
}

type VoucherGroup struct {
	ID         int64
	ProviderID int64
	Name       string
}

type VouchersFt struct {
	Username string
}
