// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const countVouchers = `-- name: CountVouchers :one
SELECT COUNT(*) FROM vouchers v
JOIN voucher_groups vg ON vg.id = v.group_id
JOIN providers p ON p.id = vg.provider_id
WHERE (?1 IS NULL OR v.state = ?1)
  AND (?2 IS NULL OR v.validity = ?2)
  AND (?3 IS NULL OR v.printed = ?3)
  AND (?4 IS NULL OR vg.name = ?4)
  AND (
    ?5 IS NULL OR v.id IN (
      SELECT rowid FROM vouchers_fts WHERE vouchers_fts.username MATCH ?5 || '*'
    )
  )
`

type CountVouchersParams struct {
	State     interface{}
	Validity  interface{}
	Printed   interface{}
	GroupName interface{}
	Search    interface{}
}

func (q *Queries) CountVouchers(ctx context.Context, arg CountVouchersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVouchers,
		arg.State,
		arg.Validity,
		arg.Printed,
		arg.GroupName,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExpiredVouchersPerDay = `-- name: GetExpiredVouchersPerDay :many
SELECT
    strftime('%w', datetime(endtime, 'unixepoch')) as day_of_week,
    validity,
    COUNT(*) as count
FROM vouchers
WHERE state = 'expired'
  AND endtime >= ? AND endtime <= ?
GROUP BY day_of_week, validity
ORDER BY day_of_week, validity
`

type GetExpiredVouchersPerDayParams struct {
	Endtime   sql.NullInt64
	Endtime_2 sql.NullInt64
}

type GetExpiredVouchersPerDayRow struct {
	DayOfWeek interface{}
	Validity  int64
	Count     int64
}

func (q *Queries) GetExpiredVouchersPerDay(ctx context.Context, arg GetExpiredVouchersPerDayParams) ([]GetExpiredVouchersPerDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredVouchersPerDay, arg.Endtime, arg.Endtime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredVouchersPerDayRow
	for rows.Next() {
		var i GetExpiredVouchersPerDayRow
		if err := rows.Scan(&i.DayOfWeek, &i.Validity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredVouchersPerMonth = `-- name: GetExpiredVouchersPerMonth :many
SELECT
    strftime('%Y-%m', datetime(endtime, 'unixepoch')) as month,
    validity,
    COUNT(*) as count
FROM vouchers
WHERE state = 'expired'
  AND endtime >= ? AND endtime <= ?
GROUP BY month, validity
ORDER BY month, validity
`

type GetExpiredVouchersPerMonthParams struct {
	Endtime   sql.NullInt64
	Endtime_2 sql.NullInt64
}

type GetExpiredVouchersPerMonthRow struct {
	Month    interface{}
	Validity int64
	Count    int64
}

func (q *Queries) GetExpiredVouchersPerMonth(ctx context.Context, arg GetExpiredVouchersPerMonthParams) ([]GetExpiredVouchersPerMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredVouchersPerMonth, arg.Endtime, arg.Endtime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredVouchersPerMonthRow
	for rows.Next() {
		var i GetExpiredVouchersPerMonthRow
		if err := rows.Scan(&i.Month, &i.Validity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredVouchersPerWeek = `-- name: GetExpiredVouchersPerWeek :many
SELECT
    strftime('%Y-%W', datetime(endtime, 'unixepoch')) as week,
    validity,
    COUNT(*) as count
FROM vouchers
WHERE state = 'expired'
  AND endtime >= ? AND endtime <= ?
GROUP BY week, validity
ORDER BY week, validity
`

type GetExpiredVouchersPerWeekParams struct {
	Endtime   sql.NullInt64
	Endtime_2 sql.NullInt64
}

type GetExpiredVouchersPerWeekRow struct {
	Week     interface{}
	Validity int64
	Count    int64
}

func (q *Queries) GetExpiredVouchersPerWeek(ctx context.Context, arg GetExpiredVouchersPerWeekParams) ([]GetExpiredVouchersPerWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredVouchersPerWeek, arg.Endtime, arg.Endtime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredVouchersPerWeekRow
	for rows.Next() {
		var i GetExpiredVouchersPerWeekRow
		if err := rows.Scan(&i.Week, &i.Validity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvidersDetails = `-- name: GetProvidersDetails :one
SELECT id, name FROM providers
WHERE name = ? LIMIT 1
`

func (q *Queries) GetProvidersDetails(ctx context.Context, name sql.NullString) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvidersDetails, name)
	var i Provider
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getProvidersList = `-- name: GetProvidersList :many
SELECT id, name FROM providers
ORDER BY name
`

func (q *Queries) GetProvidersList(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, getProvidersList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSearchProviders = `-- name: GetSearchProviders :many
SELECT id, name FROM providers
WHERE name LIKE CONCAT('%', ?, '%')
`

func (q *Queries) GetSearchProviders(ctx context.Context, concat interface{}) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, getSearchProviders, concat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoucherByID = `-- name: GetVoucherByID :one
SELECT
    v.id,
    v.username,
    v.validity,
    v.state,
    v.printed,
    vg.name AS group_name,
    p.name AS provider_name
FROM vouchers v
JOIN voucher_groups vg ON vg.id = v.group_id
JOIN providers p ON p.id = vg.provider_id
WHERE v.id = ? LIMIT 1
`

type GetVoucherByIDRow struct {
	ID           int64
	Username     string
	Validity     int64
	State        string
	Printed      string
	GroupName    string
	ProviderName sql.NullString
}

func (q *Queries) GetVoucherByID(ctx context.Context, id int64) (GetVoucherByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVoucherByID, id)
	var i GetVoucherByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Validity,
		&i.State,
		&i.Printed,
		&i.GroupName,
		&i.ProviderName,
	)
	return i, err
}

const getVouchersList = `-- name: GetVouchersList :many
SELECT vouchers.id, group_id, username, validity, expirytime, starttime, endtime, printed, state, voucher_groups.id, provider_id, name FROM vouchers
JOIN voucher_groups ON vouchers.group_id = voucher_groups.id
ORDER BY vouchers.id
`

type GetVouchersListRow struct {
	ID         int64
	GroupID    int64
	Username   string
	Validity   int64
	Expirytime sql.NullInt64
	Starttime  sql.NullFloat64
	Endtime    sql.NullInt64
	Printed    string
	State      string
	ID_2       int64
	ProviderID int64
	Name       string
}

func (q *Queries) GetVouchersList(ctx context.Context) ([]GetVouchersListRow, error) {
	rows, err := q.db.QueryContext(ctx, getVouchersList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVouchersListRow
	for rows.Next() {
		var i GetVouchersListRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Username,
			&i.Validity,
			&i.Expirytime,
			&i.Starttime,
			&i.Endtime,
			&i.Printed,
			&i.State,
			&i.ID_2,
			&i.ProviderID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupNameListUniqueVouchers = `-- name: GroupNameListUniqueVouchers :many
SELECT DISTINCT vg.name
FROM voucher_groups vg
INNER JOIN vouchers v ON v.group_id = vg.id
WHERE (?1 IS NULL OR v.validity = ?1)
ORDER BY vg.name ASC
`

func (q *Queries) GroupNameListUniqueVouchers(ctx context.Context, validity interface{}) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, groupNameListUniqueVouchers, validity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVouchers = `-- name: ListVouchers :many
SELECT
    v.id,
    v.username,
    v.validity,
    v.state,
    v.printed,
    vg.name AS group_name,
    p.name AS provider_name
FROM vouchers v
JOIN voucher_groups vg ON vg.id = v.group_id
JOIN providers p ON p.id = vg.provider_id
WHERE (?1 IS NULL OR v.state = ?1)
  AND (?2 IS NULL OR v.validity = ?2)
  AND (?3 IS NULL OR v.printed = ?3)
  AND (?4 IS NULL OR vg.name = ?4)
  AND (
    ?5 IS NULL OR v.id IN (
      SELECT rowid FROM vouchers_fts WHERE vouchers_fts.username MATCH ?5 || '*'
    )
  )
LIMIT ?7 OFFSET ?6
`

type ListVouchersParams struct {
	State     interface{}
	Validity  interface{}
	Printed   interface{}
	GroupName interface{}
	Search    interface{}
	Offset    int64
	Limit     int64
}

type ListVouchersRow struct {
	ID           int64
	Username     string
	Validity     int64
	State        string
	Printed      string
	GroupName    string
	ProviderName sql.NullString
}

func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]ListVouchersRow, error) {
	rows, err := q.db.QueryContext(ctx, listVouchers,
		arg.State,
		arg.Validity,
		arg.Printed,
		arg.GroupName,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVouchersRow
	for rows.Next() {
		var i ListVouchersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Validity,
			&i.State,
			&i.Printed,
			&i.GroupName,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const printedListUniqueVouchers = `-- name: PrintedListUniqueVouchers :many
SELECT DISTINCT printed
FROM vouchers
ORDER BY state ASC
`

func (q *Queries) PrintedListUniqueVouchers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, printedListUniqueVouchers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var printed string
		if err := rows.Scan(&printed); err != nil {
			return nil, err
		}
		items = append(items, printed)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stateListUniqueVouchers = `-- name: StateListUniqueVouchers :many
SELECT DISTINCT state
FROM vouchers
ORDER BY state ASC
`

func (q *Queries) StateListUniqueVouchers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, stateListUniqueVouchers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var state string
		if err := rows.Scan(&state); err != nil {
			return nil, err
		}
		items = append(items, state)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVouchersPrintedField = `-- name: UpdateVouchersPrintedField :exec
UPDATE vouchers
set printed = 'printed'
WHERE id = ?
`

func (q *Queries) UpdateVouchersPrintedField(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateVouchersPrintedField, id)
	return err
}

const validityListUniqueVouchers = `-- name: ValidityListUniqueVouchers :many
SELECT DISTINCT validity
FROM vouchers
ORDER BY validity ASC
`

func (q *Queries) ValidityListUniqueVouchers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, validityListUniqueVouchers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var validity int64
		if err := rows.Scan(&validity); err != nil {
			return nil, err
		}
		items = append(items, validity)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
